config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'lists#index'
  resources :lists do
    resources :bookmarks, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'is already in the list' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="main">
  <div class="container ms-0 w-75">
    <h1 class="mt-4 ms-0">Create A New Movie List</h1>
    <div class="container ms-0 w-75">
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.association :movie %>
        <%= f.input :comment %>
        <%= f.submit "Submit", class: "btn btn-primary justify-content-end" %>
        <%= link_to 'Back', @list, class:"btn btn-dark" %>
      <% end %>
    </div>
  </div>

  <div class="mt-3 text-center">
    <div style="width:0;height:0;padding-bottom:0;"><iframe src="https://giphy.com/embed/3o7btRGIgLc7KPTd5u" width="65%" height="55%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/zooey-deschanel-joseph-gordon-levitt-500-days-of-summer-vaRCdgM0fLNrW"></a></p>
  </div>

</div>

  <div class="footer">
      <div class="footer-links">
        <a href="https://github.com/dancosta-fed"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com/_dancosta_/"><i class="fab fa-instagram"></i></a>
        <a href="https://www.linkedin.com/in/daniel-de-oliveira-costa-590515140/"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        Created by &copy Dan Costa
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="container w-75">
  <h1 class="mt-4 text-center">Edit your Movie List</h1>

  <div class="container w-75">
    <%= simple_form_for [@list] do |l| %>
      <%= l.input :name %>
      <%= l.submit "Update", class: "btn btn-primary" %>
      <%= link_to 'Back', lists_path, class:"btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/lists/index.html.erb
<div class="wrapper">

  <div class="banner">
    <div class="banner-content container">
    <h1 class="main-title">Make your own Movie List</h1>
    </div>
  </div>

  <div class="container py-5">
    <div class="d-flex align-items-center justify-content-between mb-3">
      <h1 class="mb-0">Movie Lists</h1>
      <%= link_to 'Add New', new_list_path, class: "btn btn-success mt-3" %>
    </div>

      <div class="row my-2">
        <% @lists.each do |list| %>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4" data-aos="zoom-in">
            <div class="bg-white rounded shadow h-30">
          <%= link_to list_path(list), class: "text-decoration-none" do %>
            <div class="card-category text-center">
              <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path("https://res.cloudinary.com/dognkye6x/image/upload/v1645840712/freddy_i1qye8.jpg") %>)">
              <%= list.name %>
              </div>
            </div>
          <% end %>
            </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/dancosta-fed"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/_dancosta_/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.linkedin.com/in/daniel-de-oliveira-costa-590515140/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Created by &copy Dan Costa
  </div>
</div>
</div>


<!-- 
<div class="card" style= "background-image: black, url(<%#= list.photo.attached? ? cl_image_path(list.photo.key) : asset_path("feature.jpeg") %>)" >
--> 

app/views/lists/new.html.erb
<main>
  <div>
    <div class="container ms-0 w-75">
    <h1 class="mt-4">Create A New Movie List</h1>

    <div class="container ms-0 w-75">
      <%= simple_form_for [@list] do |l| %>
        <%= l.input :name, placeholder: 'Thriller...'%>
        <%= l.submit "Create", class: "btn btn-primary" %>
        <%= link_to 'Back', lists_path, class:"btn btn-dark" %>
      <% end %>
    </div>
  </div>

  <div class="mt-3 text-center">
    <div style="width:0;height:0;padding-bottom:0;"><iframe src="https://giphy.com/embed/vaRCdgM0fLNrW" width="65%" height="55%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/zooey-deschanel-joseph-gordon-levitt-500-days-of-summer-vaRCdgM0fLNrW"></a></p>
  </div>
</main>

  <footer class="footer">
      <div class="footer-links">
        <a href="https://github.com/dancosta-fed"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com/_dancosta_/"><i class="fab fa-instagram"></i></a>
        <a href="https://www.linkedin.com/in/daniel-de-oliveira-costa-590515140/"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        Created by &copy Dan Costa
      </div>
  </footer>
</div>

app/views/lists/show.html.erb
<div class="wrapper">

<div class="container text-center mt-4">

  <div class="row">
    <h1>Here's your list</h1>
      <div class="mb-5">
    <div class="container d-flex justify-content-end">
      <p><%= link_to 'Add New Movie', 
                      new_list_bookmark_path(@list), 
                      class: "btn btn-success mt-3" %>
        </p>
    </div>
    <h2><%= @list.name %></h2>

    <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4" data-aos="zoom-in">
        <div class="poster bg-white rounded shadow h-30">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">

          <div class="col">
            <strong><%= movie.title %></strong>
          </div>

            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>

            <div class="col">
            <span class="text-muted font-weight-normal"> <em>rating:</em> <%= movie.rating %> 
            <i class="fas fa-star star-yellow"></i></span>
          </div>
              <%# Add here a delete btn %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  </div>

    <div class="col mb-4">
        <%= link_to 'Back', lists_path, class:"btn btn-dark mt-3" %>
        <%= link_to "Remove List", list_path(@list),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  notice: 'Restaurant was successfully destroyed.',
                  class: "btn btn-danger mt-3"
        %>
    </div>
  </div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/dancosta-fed"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/_dancosta_/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.linkedin.com/in/daniel-de-oliveira-costa-590515140/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Created by &copy Dan Costa
  </div>
</div>
</div>